/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dubiumview;

import java.text.SimpleDateFormat;

/**
 *
 * @author Cedup 05
 */
public class AgendamentoCamping3 extends javax.swing.JFrame {

    /**
     * Creates new form AgendamentoQuadraPoli
     */
    public AgendamentoCamping3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabelavolei = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        tNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbHorario = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bBuscar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 0));
        jLabel1.setText("Area de Camping 3");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 20, 300, 50);

        Tabelavolei.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {7, null, null, null},
                {8, null, null, null},
                {9, null, null, null},
                {10, null, null, null},
                {11,null, null, null}
            },
            new String [] {
                "Horário", "Segunda", "Terça", "Quarta", "Quinta"
            }
        ));
        jScrollPane1.setViewportView(Tabelavolei);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 160, 620, 300);

        jLabel3.setText("Nome");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 80, 50, 20);
        getContentPane().add(tNome);
        tNome.setBounds(140, 100, 200, 20);

        jLabel4.setText("Horário");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(500, 80, 60, 14);

        cbHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Selecione um horário", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00" }));
        getContentPane().add(cbHorario);
        cbHorario.setBounds(500, 100, 80, 20);

        jLabel5.setText("Dia da Semana");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(380, 80, 100, 14);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Selecione um dia", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sabado", "Domingo" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(380, 100, 90, 20);

        jButton1.setText("Agendar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(583, 500, 120, 23);

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(80, 500, 80, 23);

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(bBuscar);
        bBuscar.setBounds(620, 100, 80, 23);

        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 51, 0), 4));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 790, 560);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dubiumicons/interfacedefundo.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-120, -180, 970, 920);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  public void pegar_dados() {

       /* 
        eventopojo.setNome_evento(campoEvento.getText());
        eventopojo.setInstituicao(campoInstituiçao.getText());
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String dataformatada = sdf.format(this.campoData.getDate());
        eventopojo.setInicio(dataformatada);
        eventopojo.setFim(dataformatada);
     }
    
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
//        List lista = ambientedao.buscarambiente(cbHorario.getItemAt(WIDTH));
//
  //      for(int i=0; i<lista.size();i++){
    //        ambientepojo ambientepojo = (ambientepojo)lista.get(i);
      //      DefaultTableModel dtm = (DefaultTableModel)Tabelavolei.getModel();
        //    dtm.addRow(new Object[]{ambientepojo.getId_ambiente(),
          //      ambientepojo.getNome_ambiente(), ambientepojo.getHorario_funcionamento(),
       //         ambientepojo.getCapacidade()});
       // }
        // TODO add your handling code here:
    }//GEN-LAST:event_bBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendamentoCamping3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendamentoCamping3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendamentoCamping3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendamentoCamping3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendamentoCamping3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabelavolei;
    private javax.swing.JButton bBuscar;
    private javax.swing.JComboBox<String> cbHorario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tNome;
    // End of variables declaration//GEN-END:variables
}
