/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package dubiumview;

import dubiumpojo.pessoapojo;
import dubiumdao.pessoadao;
import dubiummodel.pessoamodel;
import javax.swing.JOptionPane;


/**
 *
 * @author Cedup 05
 */
public class AlterarPessoa extends javax.swing.JFrame {
    pessoapojo pessoapojo = new pessoapojo();
    pessoamodel pessoamodel = new pessoamodel();
    pessoadao pessoadao = new pessoadao();
    
    /** Creates new form JFrame */
     public AlterarPessoa(pessoapojo upojo) {
        initComponents();
        pessoapojo= upojo;
        carregardados();
        pessoapojo = upojo;
        
    }

    //AlterarPessoa() {
     //    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    //}
    public void carregardados(){
        
        tEmail.setText(""+pessoapojo.getEmail());
        tTelefone.setText(""+pessoapojo.getTelefone());
        tLogin.setText(""+pessoapojo.getLogin());
        
    }
    
     public void limparCampos(){
        tSenha.setText("");
        tConfirmar.setText("");
        tTelefone.setText("");
        tEmail.setText("");
        tLogin.setText("");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lEmail = new javax.swing.JLabel();
        lTelefone = new javax.swing.JLabel();
        lLogin = new javax.swing.JLabel();
        lSenha = new javax.swing.JLabel();
        tEmail = new javax.swing.JTextField();
        tTelefone = new javax.swing.JTextField();
        tLogin = new javax.swing.JTextField();
        bAtualizar = new javax.swing.JButton();
        bSair = new javax.swing.JButton();
        lConfirmar = new javax.swing.JLabel();
        bLimpar = new javax.swing.JButton();
        tSenha = new javax.swing.JPasswordField();
        tConfirmar = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Alterar Dados");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 40, 320, 30);

        lEmail.setText("Novo Email");
        getContentPane().add(lEmail);
        lEmail.setBounds(50, 140, 80, 14);

        lTelefone.setText("Novo Telefone");
        getContentPane().add(lTelefone);
        lTelefone.setBounds(50, 200, 110, 14);

        lLogin.setText("Novo Login");
        getContentPane().add(lLogin);
        lLogin.setBounds(330, 100, 90, 14);

        lSenha.setText("Nova Senha");
        getContentPane().add(lSenha);
        lSenha.setBounds(330, 160, 90, 14);
        getContentPane().add(tEmail);
        tEmail.setBounds(50, 160, 200, 20);
        getContentPane().add(tTelefone);
        tTelefone.setBounds(50, 220, 200, 20);
        getContentPane().add(tLogin);
        tLogin.setBounds(330, 120, 200, 20);

        bAtualizar.setText("Atualizar Dados");
        bAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(bAtualizar);
        bAtualizar.setBounds(390, 290, 140, 23);

        bSair.setText("Sair");
        bSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairActionPerformed(evt);
            }
        });
        getContentPane().add(bSair);
        bSair.setBounds(50, 290, 60, 23);

        lConfirmar.setText("Confirmar Senha");
        getContentPane().add(lConfirmar);
        lConfirmar.setBounds(330, 220, 120, 14);

        bLimpar.setText("Limpar");
        bLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimparActionPerformed(evt);
            }
        });
        getContentPane().add(bLimpar);
        bLimpar.setBounds(120, 290, 80, 23);
        getContentPane().add(tSenha);
        tSenha.setBounds(330, 180, 200, 20);
        getContentPane().add(tConfirmar);
        tConfirmar.setBounds(330, 240, 200, 20);

        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 0), 4, true));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 570, 380);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dubiumicons/interfacedefundo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-120, 0, 690, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

        
        public void pegar_dados(){
        pessoapojo.setId_pessoa(pessoapojo.getId_pessoa());
        pessoapojo.setEmail(tEmail.getText());
        pessoapojo.setTelefone(tTelefone.getText());
        pessoapojo.setLogin(tLogin.getText());

        
    }
    private void bAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtualizarActionPerformed
        
        if(new String(tSenha.getPassword()).equals(new String(tConfirmar.getPassword()))) {
        pegar_dados();
             try {
            pessoamodel.verificar_campos(pessoapojo);
            pessoadao.alterarcontato(pessoapojo);
            JOptionPane.showMessageDialog(null, "O usuário foi alterado com sucesso!");
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, "O campo "+e.getMessage()+" é Obrigatório");
        }} else{
            JOptionPane.showMessageDialog(null, "As senhas inseridas não são identicas");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bAtualizarActionPerformed

    private void bSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairActionPerformed
        this.setVisible(false);
//        AlterarPessoa teste = new AlterarPessoa();
//        teste.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_bSairActionPerformed

    private void bLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimparActionPerformed
        limparCampos();
        // TODO add your handling code here:
    }//GEN-LAST:event_bLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new AlterarPessoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtualizar;
    private javax.swing.JButton bLimpar;
    private javax.swing.JButton bSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lConfirmar;
    private javax.swing.JLabel lEmail;
    private javax.swing.JLabel lLogin;
    private javax.swing.JLabel lSenha;
    private javax.swing.JLabel lTelefone;
    private javax.swing.JPasswordField tConfirmar;
    private javax.swing.JTextField tEmail;
    private javax.swing.JTextField tLogin;
    private javax.swing.JPasswordField tSenha;
    private javax.swing.JTextField tTelefone;
    // End of variables declaration//GEN-END:variables

}
