/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dubiumview;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Cedup 05
 */
public class ambientes extends javax.swing.JInternalFrame {
    
//    AlterarPessoa teste1 = new AlterarPessoa();
    AgendamentoVoleiAreia agendamentovolei = new AgendamentoVoleiAreia();

    /**
     * Creates new form ambientes
     */
    public ambientes() {
         
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bSair = new javax.swing.JButton();
        lDeck = new javax.swing.JLabel();
        lFutebol_Areia = new javax.swing.JLabel();
        lBocha = new javax.swing.JLabel();
        lQuadra = new javax.swing.JLabel();
        lVolei = new javax.swing.JLabel();
        lFutebol = new javax.swing.JLabel();
        lChurrasqueira = new javax.swing.JLabel();
        lCamping = new javax.swing.JLabel();
        lFundo = new javax.swing.JLabel();
        areadetrabalho = new javax.swing.JDesktopPane();

        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 51, 0)));
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(null);

        bSair.setText("Sair");
        bSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairActionPerformed(evt);
            }
        });
        getContentPane().add(bSair);
        bSair.setBounds(1210, 510, 110, 23);

        lDeck.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lDeck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lDeckMouseClicked(evt);
            }
        });
        getContentPane().add(lDeck);
        lDeck.setBounds(400, 40, 229, 158);

        lFutebol_Areia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lFutebol_Areia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lFutebol_AreiaMouseClicked(evt);
            }
        });
        getContentPane().add(lFutebol_Areia);
        lFutebol_Areia.setBounds(760, 340, 229, 157);

        lBocha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lBocha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lBochaMouseClicked(evt);
            }
        });
        getContentPane().add(lBocha);
        lBocha.setBounds(1100, 40, 224, 158);

        lQuadra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lQuadra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lQuadraMouseClicked(evt);
            }
        });
        getContentPane().add(lQuadra);
        lQuadra.setBounds(50, 40, 230, 158);

        lVolei.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lVolei.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lVoleiMouseClicked(evt);
            }
        });
        getContentPane().add(lVolei);
        lVolei.setBounds(50, 340, 231, 161);

        lFutebol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lFutebol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lFutebolMouseClicked(evt);
            }
        });
        getContentPane().add(lFutebol);
        lFutebol.setBounds(400, 340, 241, 158);

        lChurrasqueira.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lChurrasqueira.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lChurrasqueiraMouseClicked(evt);
            }
        });
        getContentPane().add(lChurrasqueira);
        lChurrasqueira.setBounds(760, 40, 229, 158);

        lCamping.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lCamping.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lCampingMouseClicked(evt);
            }
        });
        getContentPane().add(lCamping);
        lCamping.setBounds(1090, 340, 230, 157);

        lFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dubiumicons/Seja Bem-Vindo! (2).png"))); // NOI18N
        getContentPane().add(lFundo);
        lFundo.setBounds(0, -50, 1420, 620);
        getContentPane().add(areadetrabalho);
        areadetrabalho.setBounds(0, -30, 1390, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairActionPerformed
        this.dispose();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_bSairActionPerformed

    private void lVoleiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lVoleiMouseClicked
        AgendamentoVoleiAreia agendamentoVoleiAreia = new AgendamentoVoleiAreia();
        agendamentoVoleiAreia.setVisible(true);
        agendamentoVoleiAreia.setSize(790,560);
        agendamentoVoleiAreia.setLocationRelativeTo(null);
       
        
//        teste1.setContentPane( agendamentovolei );
//        teste1.setVisible(true);
//        teste1.setSize(801,561);
//        

        // TODO add your handling code here:
    }//GEN-LAST:event_lVoleiMouseClicked

    private void lCampingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lCampingMouseClicked
        MapaCamping mapacamping = new MapaCamping();
        mapacamping.setVisible(true);
        mapacamping.setSize(1078,518);
        mapacamping.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_lCampingMouseClicked

    private void lDeckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lDeckMouseClicked
        AgendamentoDeck deck = new AgendamentoDeck();
        deck.setVisible(true);
        deck.setSize(790,560);
        deck.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_lDeckMouseClicked

    private void lQuadraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lQuadraMouseClicked
        AgendamentoQuadraPoliesportiva poliesportiva = new AgendamentoQuadraPoliesportiva();
        poliesportiva.setVisible(true);
        poliesportiva.setSize(790,560);
        poliesportiva.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_lQuadraMouseClicked

    private void lChurrasqueiraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lChurrasqueiraMouseClicked
        AgendamentoChurrasqueira churrasqueira = new AgendamentoChurrasqueira();
        churrasqueira.setVisible(true);
        churrasqueira.setSize(790,560);
        churrasqueira.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_lChurrasqueiraMouseClicked

    private void lBochaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lBochaMouseClicked
        AgendamentoQuadraBocha bocha = new AgendamentoQuadraBocha();
        bocha.setVisible(true);
        bocha.setSize(790,560);
        bocha.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_lBochaMouseClicked

    private void lFutebolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lFutebolMouseClicked
        AgendamentoCampo campo = new AgendamentoCampo();
        campo.setVisible(true);
        campo.setSize(790,560);
        campo.setLocationRelativeTo(null);
           // TODO add your handling code here:
    }//GEN-LAST:event_lFutebolMouseClicked

    private void lFutebol_AreiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lFutebol_AreiaMouseClicked
        AgendamentoFutebolAreia futebolareia = new AgendamentoFutebolAreia();
        futebolareia.setVisible(true);
        futebolareia.setSize(790,560);
        futebolareia.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_lFutebol_AreiaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane areadetrabalho;
    private javax.swing.JButton bSair;
    private javax.swing.JLabel lBocha;
    private javax.swing.JLabel lCamping;
    private javax.swing.JLabel lChurrasqueira;
    private javax.swing.JLabel lDeck;
    private javax.swing.JLabel lFundo;
    private javax.swing.JLabel lFutebol;
    private javax.swing.JLabel lFutebol_Areia;
    private javax.swing.JLabel lQuadra;
    private javax.swing.JLabel lVolei;
    // End of variables declaration//GEN-END:variables
}
