 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dubiumview;

import javax.swing.JOptionPane;
import javax.swing.JTextField;
import dubiumpojo.pessoapojo;
import dubiummodel.pessoamodel;
import dubiumdao.pessoadao;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.print.event.PrintJobEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Win10
 */
public class BuscarPessoa extends javax.swing.JInternalFrame {
    pessoadao pessoadao = new pessoadao();
    pessoapojo pessoapojo = new pessoapojo();
    
            

    /**
     * Creates new form UsuarioExcluir
     */
    public BuscarPessoa() {
        
     
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lNome = new javax.swing.JLabel();
        bExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        tNome = new javax.swing.JTextField();
        bBuscar = new javax.swing.JButton();
        bLimpar = new javax.swing.JButton();
        bVerDados = new javax.swing.JButton();
        bAlterar = new javax.swing.JButton();
        bSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 0), 4, true));
        setClosable(true);
        setTitle("Excluir Usuário");
        getContentPane().setLayout(null);

        lNome.setText("Nome");
        getContentPane().add(lNome);
        lNome.setBounds(140, 20, 60, 14);

        bExcluir.setText("Excluir");
        bExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(bExcluir);
        bExcluir.setBounds(670, 400, 80, 23);

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_pessoa", "Nome", "nivel_acesso", "Email", "Telefone"
            }
        ));
        Tabela.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Tabela);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(140, 90, 610, 260);

        tNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNomeActionPerformed(evt);
            }
        });
        getContentPane().add(tNome);
        tNome.setBounds(140, 40, 470, 20);

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(bBuscar);
        bBuscar.setBounds(660, 40, 80, 23);

        bLimpar.setText("Limpar Busca");
        bLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimparActionPerformed(evt);
            }
        });
        getContentPane().add(bLimpar);
        bLimpar.setBounds(220, 400, 130, 23);

        bVerDados.setText("Ver dados");
        bVerDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVerDadosActionPerformed(evt);
            }
        });
        getContentPane().add(bVerDados);
        bVerDados.setBounds(480, 400, 100, 23);

        bAlterar.setText("Alterar");
        bAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(bAlterar);
        bAlterar.setBounds(590, 400, 73, 23);

        bSair.setText("Sair");
        bSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairActionPerformed(evt);
            }
        });
        getContentPane().add(bSair);
        bSair.setBounds(140, 400, 70, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dubiumicons/interfacedefundo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-130, -50, 1220, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExcluirActionPerformed
         if(Tabela.getSelectedRow()<0){
            JOptionPane.showMessageDialog(null, "É obrigatório a seleção de uma linha");
        }
        else {
             
            int linha=Tabela.getSelectedRow();
            int id_pessoa=Integer.parseInt(""+Tabela.getValueAt(linha, 0));
            String nome=""+Tabela.getValueAt(linha, 1);
            int ok=JOptionPane.showConfirmDialog(null, "Deseja Realmente "
            +"excluir o contato de "+nome);
            if (ok==0){
                pessoadao.RemoverContato(id_pessoa);
                //LimparTabela();
                //BuscaAutomatica();
            }
            System.out.println(""+pessoapojo.getId_pessoa());
                    
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_bExcluirActionPerformed

    private void tNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNomeActionPerformed

    private void bSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_bSairActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
           List lista = pessoadao.buscarContatos(tNome.getText());
           
        for(int i=0; i<lista.size();i++){
            pessoapojo pessoapojo = (pessoapojo)lista.get(i);
            DefaultTableModel dtm = (DefaultTableModel)Tabela.getModel();
            dtm.addRow(new Object[]{pessoapojo.getId_pessoa(),
                pessoapojo.getNome(),
                pessoapojo.getNivel_acesso(), 
                pessoapojo.getEmail(),
                pessoapojo.getTelefone(),
                });
        }
// TODO add your handling code here:
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAlterarActionPerformed
        
        if(Tabela.getSelectedRow()<0){
            JOptionPane.showMessageDialog(null, "É obrigatório a seleção de uma linha");
        }
        else {
        int linha=Tabela.getSelectedRow();
        int dado=Integer.parseInt(""+Tabela.getValueAt(linha, 0));
        pessoapojo= pessoadao.BuscarContatoUnico(dado);
        
        AlterarPessoa alterarpessoa = new AlterarPessoa(pessoapojo);
        alterarpessoa.setVisible(true);
        alterarpessoa.setSize(571,380);
        alterarpessoa.setLocationRelativeTo(null);
        
        //areadetrabalho.add(usuarioalterar);
        this.dispose();
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_bAlterarActionPerformed

    private void bLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimparActionPerformed
        tNome.setText(null);
    }//GEN-LAST:event_bLimparActionPerformed

    private void bVerDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVerDadosActionPerformed
         if (Tabela.getSelectedRow()<0){
            JOptionPane.showMessageDialog(null, "é necessário selecionar a um registro");
        }
        else{
           int linha=Tabela.getSelectedRow();
        Object dado=Tabela.getValueAt(linha,0);
        int idContato=Integer.parseInt(""+dado);
            pessoapojo = pessoadao.BuscarContatoUnico(idContato);
          JOptionPane.showMessageDialog(null,
                   
                     "Nivel de Acesso: "+pessoapojo.getNivel_acesso()+"\n"         
                   +"Nome: "+pessoapojo.getNome()+"\n"
                   +"Data de Nascimento: "+pessoapojo.getData_nascimento()+"\n"   
                   +"Email: "+pessoapojo.getEmail()+"\n"
                   +"Sexo: "+pessoapojo.getSexo()+"\n"
                   +"Telefone: "+pessoapojo.getTelefone());
         }
    }//GEN-LAST:event_bVerDadosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela;
    private javax.swing.JButton bAlterar;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bExcluir;
    private javax.swing.JButton bLimpar;
    private javax.swing.JButton bSair;
    private javax.swing.JButton bVerDados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lNome;
    private javax.swing.JTextField tNome;
    // End of variables declaration//GEN-END:variables
}
