/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dubiumview;

import dubiumdao.funcionariodao;
import java.util.Arrays;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import dubiumpojo.pessoapojo;
import dubiummodel.pessoamodel;
import dubiumdao.pessoadao;
import dubiummodel.funcionariomodel;
import dubiumpojo.funcionariopojo;
import java.text.SimpleDateFormat;

/**
 *
 * @author Cedup 05
 */
public class CadastroFuncionario extends javax.swing.JInternalFrame {
    funcionariodao funcionariodao = new funcionariodao();
    funcionariopojo funcionariopojo = new funcionariopojo();
    funcionariomodel funcionariomodel = new funcionariomodel();
    
    pessoadao pessoadao = new pessoadao();
    pessoapojo pessoapojo = new pessoapojo();
    pessoamodel pessoamodel = new pessoamodel();

    /**
     * Creates new form CadastroVisitantes
     */
    public void limpar_campos() {
        tEmail.setText("");
        tNumero.setText("");
        tNome.setText("");
        GSexo.clearSelection();
        tSenha.setText("");
        tConfSenha.setText("");
        tPis.setText("");
        tCpf.setText("");
        dcNascimento.setDate(null);
        dcAdmissao.setDate(null);
        tLogin.setText("");
    }

    public CadastroFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GSexo = new javax.swing.ButtonGroup();
        tNome = new javax.swing.JTextField();
        lNome = new javax.swing.JLabel();
        tEmail = new javax.swing.JTextField();
        lEmail = new javax.swing.JLabel();
        lNumero = new javax.swing.JLabel();
        dcNascimento = new com.toedter.calendar.JDateChooser();
        tNumero = new javax.swing.JTextField();
        bCadastro = new javax.swing.JButton();
        bLimpar = new javax.swing.JButton();
        lNascimento = new javax.swing.JLabel();
        BRMasculino = new javax.swing.JRadioButton();
        BRFeminino = new javax.swing.JRadioButton();
        tPis = new javax.swing.JTextField();
        tSenha = new javax.swing.JPasswordField();
        tConfSenha = new javax.swing.JPasswordField();
        lSexo = new javax.swing.JLabel();
        lPis = new javax.swing.JLabel();
        lSenha = new javax.swing.JLabel();
        lConfSenha = new javax.swing.JLabel();
        tLogin = new javax.swing.JTextField();
        lLogin = new javax.swing.JLabel();
        dcAdmissao = new com.toedter.calendar.JDateChooser();
        lAdmissao = new javax.swing.JLabel();
        lCpf = new javax.swing.JLabel();
        tCpf = new javax.swing.JTextField();
        bSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lFundo = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 51, 0), 4));
        setClosable(true);
        setTitle("Cadastro de Funcionário");
        getContentPane().setLayout(null);

        tNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNomeActionPerformed(evt);
            }
        });
        getContentPane().add(tNome);
        tNome.setBounds(130, 60, 200, 20);

        lNome.setText("Nome");
        getContentPane().add(lNome);
        lNome.setBounds(130, 40, 50, 14);
        getContentPane().add(tEmail);
        tEmail.setBounds(130, 110, 200, 20);

        lEmail.setText("Email");
        getContentPane().add(lEmail);
        lEmail.setBounds(130, 90, 50, 14);

        lNumero.setText("Telefone");
        getContentPane().add(lNumero);
        lNumero.setBounds(130, 140, 60, 14);

        dcNascimento.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(dcNascimento);
        dcNascimento.setBounds(130, 210, 150, 20);

        tNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNumeroActionPerformed(evt);
            }
        });
        getContentPane().add(tNumero);
        tNumero.setBounds(130, 160, 150, 20);

        bCadastro.setText("Cadastrar");
        bCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(bCadastro);
        bCadastro.setBounds(470, 340, 100, 23);

        bLimpar.setText("Limpar");
        bLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimparActionPerformed(evt);
            }
        });
        getContentPane().add(bLimpar);
        bLimpar.setBounds(380, 340, 80, 23);

        lNascimento.setText("Data de Nascimento");
        getContentPane().add(lNascimento);
        lNascimento.setBounds(130, 190, 120, 14);

        BRMasculino.setBackground(new java.awt.Color(255, 255, 204));
        GSexo.add(BRMasculino);
        BRMasculino.setSelected(true);
        BRMasculino.setText("Masculino");
        getContentPane().add(BRMasculino);
        BRMasculino.setBounds(390, 260, 80, 23);

        BRFeminino.setBackground(new java.awt.Color(255, 255, 204));
        GSexo.add(BRFeminino);
        BRFeminino.setText("Feminino");
        BRFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRFemininoActionPerformed(evt);
            }
        });
        getContentPane().add(BRFeminino);
        BRFeminino.setBounds(470, 260, 80, 23);
        getContentPane().add(tPis);
        tPis.setBounds(130, 260, 150, 20);

        tSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(tSenha);
        tSenha.setBounds(390, 110, 150, 20);

        tConfSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tConfSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(tConfSenha);
        tConfSenha.setBounds(390, 160, 150, 20);

        lSexo.setText("Sexo");
        getContentPane().add(lSexo);
        lSexo.setBounds(390, 240, 30, 14);

        lPis.setText("Numero do Pis");
        getContentPane().add(lPis);
        lPis.setBounds(130, 240, 110, 14);

        lSenha.setText("Senha");
        getContentPane().add(lSenha);
        lSenha.setBounds(390, 90, 110, 14);

        lConfSenha.setText("Confirmar Senha");
        getContentPane().add(lConfSenha);
        lConfSenha.setBounds(390, 140, 140, 14);

        tLogin.setSelectedTextColor(new java.awt.Color(255, 255, 0));
        tLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tLoginActionPerformed(evt);
            }
        });
        getContentPane().add(tLogin);
        tLogin.setBounds(390, 60, 150, 20);

        lLogin.setText("Login");
        getContentPane().add(lLogin);
        lLogin.setBounds(390, 40, 100, 14);
        getContentPane().add(dcAdmissao);
        dcAdmissao.setBounds(390, 210, 150, 20);

        lAdmissao.setText("Data de Admissão");
        getContentPane().add(lAdmissao);
        lAdmissao.setBounds(390, 190, 100, 14);

        lCpf.setText("CPF");
        getContentPane().add(lCpf);
        lCpf.setBounds(130, 290, 70, 14);

        tCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tCpfActionPerformed(evt);
            }
        });
        getContentPane().add(tCpf);
        tCpf.setBounds(130, 310, 150, 20);

        bSair.setText("Sair");
        bSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairActionPerformed(evt);
            }
        });
        getContentPane().add(bSair);
        bSair.setBounds(300, 340, 70, 23);

        jLabel1.setText("teste");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(510, 10, 60, 20);

        lFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dubiumicons/tela de cadastro.png"))); // NOI18N
        getContentPane().add(lFundo);
        lFundo.setBounds(-130, -40, 850, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void tNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNomeActionPerformed

    public void pegar_dados(){

        pessoapojo.setNome(tNome.getText());
        pessoapojo.setEmail(tEmail.getText());
        pessoapojo.setTelefone(tNumero.getText());
        pessoapojo.setSenha(new String(tSenha.getPassword()));
        pessoapojo.setLogin(tLogin.getText());
        pessoapojo.setNivel_acesso(2);
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String dataformatada = sdf.format(this.dcAdmissao.getDate());
        funcionariopojo.setAdmissao(dataformatada);
        funcionariopojo.setCpf(tCpf.getText());
        funcionariopojo.setPis(new Integer(tPis.getText()));
         if(BRMasculino.isSelected()){
            pessoapojo.setSexo("M");
        }else{
            pessoapojo.setSexo("F");
        } 
        /////////pessoapojo.setSexo(title);
        ///////////// COMO TRATAR AS OUTRAS VARIAVEIS
    }

    private void bCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadastroActionPerformed
        pegar_dados();
        try {
            pessoamodel.verificar_campos(pessoapojo);
            funcionariomodel.verificar_campos(funcionariopojo);
            pessoadao.inserir_Pessoa_dao(pessoapojo);
            funcionariodao.inserir_Funcionario_dao(funcionariopojo);
           
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, "O campo " + e.getMessage() + " é obrigatório");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_bCadastroActionPerformed

    private void bLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimparActionPerformed
        limpar_campos();
        // TODO add your handling code here:
    }//GEN-LAST:event_bLimparActionPerformed

    private void tConfSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tConfSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tConfSenhaActionPerformed

    private void tSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tSenhaActionPerformed

    private void tNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNumeroActionPerformed

    private void tLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tLoginActionPerformed

    private void BRFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRFemininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BRFemininoActionPerformed

    private void tCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tCpfActionPerformed

    private void bSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairActionPerformed
        this.dispose();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_bSairActionPerformed
 public void Preencher() {
        tEmail.setText("funcionario@cedup");
        tNumero.setText("789456");
        tNome.setText("Alberto da Silva");
        tSenha.setText("");
        tConfSenha.setText("");
        tPis.setText("8888888");
        tCpf.setText("499555222");
        dcNascimento.setDate(null);
        dcAdmissao.setDate(null);
        tLogin.setText("funcionario");
    }
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Preencher();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BRFeminino;
    private javax.swing.JRadioButton BRMasculino;
    private javax.swing.ButtonGroup GSexo;
    private javax.swing.JButton bCadastro;
    private javax.swing.JButton bLimpar;
    private javax.swing.JButton bSair;
    private com.toedter.calendar.JDateChooser dcAdmissao;
    private com.toedter.calendar.JDateChooser dcNascimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lAdmissao;
    private javax.swing.JLabel lConfSenha;
    private javax.swing.JLabel lCpf;
    private javax.swing.JLabel lEmail;
    private javax.swing.JLabel lFundo;
    private javax.swing.JLabel lLogin;
    private javax.swing.JLabel lNascimento;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lNumero;
    private javax.swing.JLabel lPis;
    private javax.swing.JLabel lSenha;
    private javax.swing.JLabel lSexo;
    private javax.swing.JPasswordField tConfSenha;
    private javax.swing.JTextField tCpf;
    private javax.swing.JTextField tEmail;
    private javax.swing.JTextField tLogin;
    private javax.swing.JTextField tNome;
    private javax.swing.JTextField tNumero;
    private javax.swing.JTextField tPis;
    private javax.swing.JPasswordField tSenha;
    // End of variables declaration//GEN-END:variables
}
