/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dubiumview;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import dubiumdao.eventodao;
import dubiummodel.eventomodel;
import dubiumpojo.eventopojo;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFrame;

/**
 *
 * @author CEDUP16
 */
public class Cadastroagenda extends javax.swing.JFrame {
    eventomodel eventomodel = new eventomodel();
    eventopojo eventopojo = new eventopojo();
    eventodao  eventodao = new eventodao();
    /**
     * Creates new form agendasemanal
     */
    public Cadastroagenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tTabela = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        bAdicionar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoEvento = new javax.swing.JTextField();
        campoData = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        campoInstituiçao = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Agenda Semanal");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 40, 330, 30);

        tTabela.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Evento", "Instituição"
            }
        ));
        jScrollPane2.setViewportView(tTabela);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 250, 700, 140);

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(600, 420, 150, 23);

        bAdicionar.setText("Adicionar");
        bAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(bAdicionar);
        bAdicionar.setBounds(50, 420, 150, 23);

        jLabel1.setBackground(new java.awt.Color(255, 255, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 51, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 51, 0), 2));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 130, 190, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Evento");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 51, 0), 2));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 130, 190, 30);

        campoEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEventoActionPerformed(evt);
            }
        });
        getContentPane().add(campoEvento);
        campoEvento.setBounds(290, 170, 190, 20);
        getContentPane().add(campoData);
        campoData.setBounds(29, 170, 190, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 51, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Instituiçao");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 51, 0), 2));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(540, 130, 190, 30);
        getContentPane().add(campoInstituiçao);
        campoInstituiçao.setBounds(540, 170, 190, 20);

        jButton2.setText("Ver agendamento");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 420, 140, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dubiumicons/interfacedefundo2.0.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 51, 0), 4));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 780, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void campoEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEventoActionPerformed
    
     public void pegar_dados() {

        
        eventopojo.setNome_evento(campoEvento.getText());
        eventopojo.setInstituicao(campoInstituiçao.getText());
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String dataformatada = sdf.format(this.campoData.getDate());
        eventopojo.setInicio(dataformatada);
        eventopojo.setFim(dataformatada);
     }
        //JDateChooser calendario = new JDateChooser(dcNascimento.getDate(), "dd/MM/yyyy"); //Aqui ele seta a data de hoje no formato dd/mm/aaaa
         //pessoapojo.setData_nascimento(""+calendario.getDate());
        //SimpleDateFormat formatter = new SimpleDateFormat(""+dcNascimento.getDate());
        //pessoapojo.setData_nascimento(formatter.format(new Date()));
        //System.out.println(""+pessoapojo.getData_nascimento());
        //pessoapojo.setSexo(GSexo.setSelected(boolean, isIcon));
    
    
    
    private void bAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdicionarActionPerformed
      
        DefaultTableModel dtmProdutos = (DefaultTableModel) tTabela.getModel();
        Object[] dados = {campoData.getDate(),campoEvento.getText(),campoInstituiçao.getText()};
        dtmProdutos.addRow(dados);
        
        pegar_dados();
        try {
            eventomodel.verificar_campos(eventopojo);
            eventodao.Inserirevento(eventopojo);
           
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, "O campo " + e.getMessage() + " é obrigatório");
        }
        
    }//GEN-LAST:event_bAdicionarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Document document = new Document();
        
        try {
            PdfWriter.getInstance(document, new FileOutputStream("Documento.pdf"));
                   
            document.open();
            document.add(new Paragraph("O Evento foi cadastrado com sucesso:"+ "\n"
                    +"Data do Evento: " + campoData.getDateFormatString()+ "\n"
                    +"Evento: "+ campoEvento.getText()+ "\n"
                    +"Instituição:"+ campoInstituiçao.getText()+"\n"
            ));
            
                    } catch (FileNotFoundException ex) {
            System.out.println("Error:"+ex);
        } catch (DocumentException ex) {
            Logger.getLogger(AgendamentodeEventos.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
        document.close();
        }
        
        try {
            Desktop.getDesktop().open (new File("Documento.pdf"));
        } catch (IOException ex) {
            System.out.println("Error:"+ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastroagenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastroagenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastroagenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastroagenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastroagenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdicionar;
    private com.toedter.calendar.JDateChooser campoData;
    private javax.swing.JTextField campoEvento;
    private javax.swing.JTextField campoInstituiçao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tTabela;
    // End of variables declaration//GEN-END:variables
}
