/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dubiumview;

import com.toedter.calendar.JDateChooser;
import java.util.Arrays;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import dubiumpojo.pessoapojo;
import dubiummodel.pessoamodel;
import dubiumdao.pessoadao;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Cedup 05
 */
public class CadastroVisitante extends javax.swing.JFrame {

      pessoadao pessoadao = new pessoadao();
    pessoapojo pessoapojo = new pessoapojo();
    pessoamodel pessoamodel = new pessoamodel();

    /**
     * Creates new form CadastroVisitante
     */
    public void limpar_campos() {
        tEmail.setText("");
        tNumero.setText("");
        tNome.setText("");
        tLogin.setText("");
        dcNascimento.setDate(null);
        GSexo.clearSelection();
        tSenha.setText("");
        tConfSenha.setText("");
       
    }
    /**
     * Creates new form CadastrarVisitante
     */
    public CadastroVisitante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GSexo = new javax.swing.ButtonGroup();
        tLogin = new javax.swing.JTextField();
        lLogin = new javax.swing.JLabel();
        tNome = new javax.swing.JTextField();
        lNome = new javax.swing.JLabel();
        tEmail = new javax.swing.JTextField();
        lEmail = new javax.swing.JLabel();
        tNumero = new javax.swing.JTextField();
        lNumero = new javax.swing.JLabel();
        dcNascimento = new com.toedter.calendar.JDateChooser();
        lNascimento = new javax.swing.JLabel();
        lSexo = new javax.swing.JLabel();
        BRMasculino = new javax.swing.JRadioButton();
        BRFeminino = new javax.swing.JRadioButton();
        bSair = new javax.swing.JButton();
        bLimpar = new javax.swing.JButton();
        bCadastar = new javax.swing.JButton();
        tConfSenha = new javax.swing.JPasswordField();
        lConfSenha = new javax.swing.JLabel();
        tSenha = new javax.swing.JPasswordField();
        lSenha = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        tLogin.setSelectedTextColor(new java.awt.Color(255, 255, 0));
        tLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tLoginActionPerformed(evt);
            }
        });
        getContentPane().add(tLogin);
        tLogin.setBounds(390, 60, 150, 20);

        lLogin.setText("Login");
        getContentPane().add(lLogin);
        lLogin.setBounds(390, 40, 100, 14);

        tNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNomeActionPerformed(evt);
            }
        });
        getContentPane().add(tNome);
        tNome.setBounds(130, 60, 200, 20);

        lNome.setText("Nome");
        getContentPane().add(lNome);
        lNome.setBounds(130, 40, 50, 14);
        getContentPane().add(tEmail);
        tEmail.setBounds(130, 110, 200, 20);

        lEmail.setText("Email");
        getContentPane().add(lEmail);
        lEmail.setBounds(130, 90, 50, 14);

        tNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNumeroActionPerformed(evt);
            }
        });
        getContentPane().add(tNumero);
        tNumero.setBounds(130, 160, 150, 20);

        lNumero.setText("Telefone");
        getContentPane().add(lNumero);
        lNumero.setBounds(130, 140, 60, 20);

        dcNascimento.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(dcNascimento);
        dcNascimento.setBounds(130, 210, 150, 20);

        lNascimento.setText("Data de Nascimento");
        getContentPane().add(lNascimento);
        lNascimento.setBounds(130, 190, 120, 14);

        lSexo.setText("Sexo");
        getContentPane().add(lSexo);
        lSexo.setBounds(130, 240, 30, 14);

        BRMasculino.setBackground(new java.awt.Color(255, 255, 204));
        GSexo.add(BRMasculino);
        BRMasculino.setSelected(true);
        BRMasculino.setText("Masculino");
        getContentPane().add(BRMasculino);
        BRMasculino.setBounds(130, 260, 100, 23);

        BRFeminino.setBackground(new java.awt.Color(255, 255, 204));
        GSexo.add(BRFeminino);
        BRFeminino.setText("Feminino");
        BRFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRFemininoActionPerformed(evt);
            }
        });
        getContentPane().add(BRFeminino);
        BRFeminino.setBounds(210, 260, 80, 23);

        bSair.setText("Sair");
        bSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairActionPerformed(evt);
            }
        });
        getContentPane().add(bSair);
        bSair.setBounds(321, 260, 60, 23);

        bLimpar.setText("Limpar");
        bLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimparActionPerformed(evt);
            }
        });
        getContentPane().add(bLimpar);
        bLimpar.setBounds(390, 260, 80, 23);

        bCadastar.setText("Cadastrar");
        bCadastar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadastarActionPerformed(evt);
            }
        });
        getContentPane().add(bCadastar);
        bCadastar.setBounds(480, 260, 100, 23);
        getContentPane().add(tConfSenha);
        tConfSenha.setBounds(390, 160, 150, 20);

        lConfSenha.setText("Confirmar Senha");
        getContentPane().add(lConfSenha);
        lConfSenha.setBounds(390, 140, 140, 14);

        tSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(tSenha);
        tSenha.setBounds(390, 110, 150, 20);

        lSenha.setText("Senha");
        getContentPane().add(lSenha);
        lSenha.setBounds(390, 90, 110, 14);

        jLabel2.setText("teste");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(530, 20, 70, 30);

        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 0), 4, true));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 626, 361);

        lFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dubiumicons/tela de cadastro.png"))); // NOI18N
        getContentPane().add(lFundo);
        lFundo.setBounds(-130, -30, 850, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void pegar_dados() {

        pessoapojo.setNome(tNome.getText());
        pessoapojo.setEmail(tEmail.getText());
        pessoapojo.setTelefone(tNumero.getText());
        pessoapojo.setSenha(new String(tSenha.getPassword()));
        pessoapojo.setLogin(tLogin.getText());
        pessoapojo.setNivel_acesso(1);
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String dataformatada = sdf.format(this.dcNascimento.getDate());
        pessoapojo.setData_nascimento(dataformatada);
        if(BRMasculino.isSelected()){
            pessoapojo.setSexo("M");
        }else{
            pessoapojo.setSexo("F");
        } 
        //JDateChooser calendario = new JDateChooser(dcNascimento.getDate(), "dd/MM/yyyy"); //Aqui ele seta a data de hoje no formato dd/mm/aaaa
         //pessoapojo.setData_nascimento(""+calendario.getDate());
        //SimpleDateFormat formatter = new SimpleDateFormat(""+dcNascimento.getDate());
        //pessoapojo.setData_nascimento(formatter.format(new Date()));
        System.out.println(""+pessoapojo.getData_nascimento());
        //pessoapojo.setSexo(GSexo.setSelected(boolean, isIcon));
        

    }
    private void tLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tLoginActionPerformed

    private void tNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNomeActionPerformed

    private void tNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNumeroActionPerformed

    private void BRFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRFemininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BRFemininoActionPerformed

    private void bSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_bSairActionPerformed

    private void bLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimparActionPerformed
        limpar_campos();
        // TODO add your handling code here:
    }//GEN-LAST:event_bLimparActionPerformed

    private void bCadastarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadastarActionPerformed
        pegar_dados();
        try {
            pessoamodel.verificar_campos(pessoapojo);
            pessoadao.inserir_Pessoa_dao(pessoapojo);

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, "O campo " + e.getMessage() + " é obrigatório");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_bCadastarActionPerformed

    private void tSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tSenhaActionPerformed
 public void Preencher() {
        tEmail.setText("visitante@cedup");
        tNumero.setText("789456");
        tNome.setText("Pedro da Fonseca");
        tSenha.setText("");
        tConfSenha.setText("");
        dcNascimento.setDate(null);
        tLogin.setText("visitante");
    }
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Preencher();
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroVisitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroVisitante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BRFeminino;
    private javax.swing.JRadioButton BRMasculino;
    private javax.swing.ButtonGroup GSexo;
    private javax.swing.JButton bCadastar;
    private javax.swing.JButton bLimpar;
    private javax.swing.JButton bSair;
    private com.toedter.calendar.JDateChooser dcNascimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lConfSenha;
    private javax.swing.JLabel lEmail;
    private javax.swing.JLabel lFundo;
    private javax.swing.JLabel lLogin;
    private javax.swing.JLabel lNascimento;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lNumero;
    private javax.swing.JLabel lSenha;
    private javax.swing.JLabel lSexo;
    private javax.swing.JPasswordField tConfSenha;
    private javax.swing.JTextField tEmail;
    private javax.swing.JTextField tLogin;
    private javax.swing.JTextField tNome;
    private javax.swing.JTextField tNumero;
    private javax.swing.JPasswordField tSenha;
    // End of variables declaration//GEN-END:variables
}
