/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dubiumview;

import dubiumdao.pessoadao;
import dubiumpojo.pessoapojo;
import javax.swing.JFrame;

/**
 *
 * @author Cedup 05
 */
public class Login extends javax.swing.JFrame {

    pessoapojo pessoapojo = new pessoapojo();
    pessoadao pessoadao = new pessoadao();
    /**
     * Creates new form Login1
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lLogin = new javax.swing.JLabel();
        lSenha = new javax.swing.JLabel();
        tLogin = new javax.swing.JTextField();
        Status = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bEntrar = new javax.swing.JButton();
        bSair = new javax.swing.JButton();
        tSenha = new javax.swing.JPasswordField();
        lCriar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        lLogin.setText("Login");
        getContentPane().add(lLogin);
        lLogin.setBounds(350, 90, 60, 14);

        lSenha.setText("Senha");
        getContentPane().add(lSenha);
        lSenha.setBounds(350, 150, 60, 14);

        tLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tLoginActionPerformed(evt);
            }
        });
        getContentPane().add(tLogin);
        tLogin.setBounds(350, 110, 160, 20);

        Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Status.setText("Digite seu login e senha");
        getContentPane().add(Status);
        Status.setBounds(330, 240, 200, 30);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Não tenho uma conta");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(350, 280, 160, 14);

        bEntrar.setText("Entrar");
        bEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(bEntrar);
        bEntrar.setBounds(433, 200, 80, 23);

        bSair.setText("Sair");
        bSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairActionPerformed(evt);
            }
        });
        getContentPane().add(bSair);
        bSair.setBounds(351, 200, 60, 23);
        getContentPane().add(tSenha);
        tSenha.setBounds(350, 170, 160, 20);

        lCriar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lCriar.setForeground(new java.awt.Color(102, 51, 0));
        lCriar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCriar.setText("CRIAR");
        lCriar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lCriar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lCriarMouseClicked(evt);
            }
        });
        getContentPane().add(lCriar);
        lCriar.setBounds(390, 300, 70, 20);

        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 0), 4, true));
        jLabel1.setPreferredSize(new java.awt.Dimension(572, 380));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 572, 380);

        lFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dubiumicons/8.png"))); // NOI18N
        getContentPane().add(lFundo);
        lFundo.setBounds(-510, -30, 1120, 410);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tLoginActionPerformed

    private void bSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairActionPerformed
        this.dispose();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_bSairActionPerformed

    private void bEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEntrarActionPerformed
        String login=tLogin.getText();
        String senha=tSenha.getText();
        
        pessoapojo = pessoadao.verificar_login(login,senha);
         System.out.println("nivel "+pessoapojo.getNivel_acesso());
        if(pessoapojo.getNivel_acesso()!=0){
            TelaInicial ti = new TelaInicial();
            ti.setVisible(true);
            ti.setExtendedState(JFrame.MAXIMIZED_BOTH);
            this.dispose();
            
        }else{
            Status.setText("LOGIN OU SENHA INCORRETO");
        }
        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_bEntrarActionPerformed

    private void lCriarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lCriarMouseClicked
        CadastroVisitante cadastrovisitante = new CadastroVisitante();
        cadastrovisitante.setVisible(true);
        cadastrovisitante.setSize(626,361);
        cadastrovisitante.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_lCriarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Status;
    private javax.swing.JButton bEntrar;
    private javax.swing.JButton bSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lCriar;
    private javax.swing.JLabel lFundo;
    private javax.swing.JLabel lLogin;
    private javax.swing.JLabel lSenha;
    private javax.swing.JTextField tLogin;
    private javax.swing.JPasswordField tSenha;
    // End of variables declaration//GEN-END:variables
}
