
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dubiumview;

import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Cedup 05
 */
public class TelaInicial extends javax.swing.JFrame {
    
    

    public TelaInicial() {
      
        initComponents();
       
        
    }


    
    
    /**
     * Creates new form TelaISnicial
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        lAmbiente = new javax.swing.JLabel();
        lLogin = new javax.swing.JLabel();
        lEvento = new javax.swing.JLabel();
        lLogo = new javax.swing.JLabel();
        lAba = new javax.swing.JLabel();
        Areadetrabalho = new javax.swing.JDesktopPane();
        lFundo = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        MCadastrar = new javax.swing.JMenu();
        IMCadastro = new javax.swing.JMenuItem();
        imCadFuncionario = new javax.swing.JMenuItem();
        imAlterar = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        imCadastroDeAgenda = new javax.swing.JMenuItem();

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lAmbiente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lAmbiente.setForeground(new java.awt.Color(255, 255, 255));
        lAmbiente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lAmbiente.setText("Ambientes");
        lAmbiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lAmbiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lAmbienteMouseClicked(evt);
            }
        });
        getContentPane().add(lAmbiente);
        lAmbiente.setBounds(190, 20, 90, 20);

        lLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lLogin.setForeground(new java.awt.Color(255, 255, 255));
        lLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lLogin.setText("Login");
        lLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lLoginMouseClicked(evt);
            }
        });
        getContentPane().add(lLogin);
        lLogin.setBounds(280, 20, 70, 20);

        lEvento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lEvento.setForeground(new java.awt.Color(255, 255, 255));
        lEvento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lEvento.setText("Eventos");
        lEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lEventoMouseClicked(evt);
            }
        });
        getContentPane().add(lEvento);
        lEvento.setBounds(110, 20, 70, 20);

        lLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lLogoMouseClicked(evt);
            }
        });
        getContentPane().add(lLogo);
        lLogo.setBounds(30, 0, 70, 70);

        lAba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dubiumicons/Aba_geral.png"))); // NOI18N
        getContentPane().add(lAba);
        lAba.setBounds(0, 0, 1400, 70);

        lFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dubiumicons/Seja Bem-Vindo1.png"))); // NOI18N

        Areadetrabalho.setLayer(lFundo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout AreadetrabalhoLayout = new javax.swing.GroupLayout(Areadetrabalho);
        Areadetrabalho.setLayout(AreadetrabalhoLayout);
        AreadetrabalhoLayout.setHorizontalGroup(
            AreadetrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AreadetrabalhoLayout.setVerticalGroup(
            AreadetrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lFundo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(Areadetrabalho);
        Areadetrabalho.setBounds(0, 67, 1400, 630);

        MCadastrar.setText("Usuário");
        MCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MCadastrarMouseEntered(evt);
            }
        });

        IMCadastro.setText("Cadastrar Usuário");
        IMCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IMCadastroActionPerformed(evt);
            }
        });
        MCadastrar.add(IMCadastro);

        imCadFuncionario.setText("Cadastrar Funcionário");
        imCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imCadFuncionarioActionPerformed(evt);
            }
        });
        MCadastrar.add(imCadFuncionario);

        imAlterar.setText("Alterar usuarios");
        imAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imAlterarActionPerformed(evt);
            }
        });
        MCadastrar.add(imAlterar);

        Menu.add(MCadastrar);

        jMenu1.setText("Agenda");

        imCadastroDeAgenda.setText("Cadastro de Agenda");
        imCadastroDeAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imCadastroDeAgendaActionPerformed(evt);
            }
        });
        jMenu1.add(imCadastroDeAgenda);

        Menu.add(jMenu1);

        setJMenuBar(Menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imAlterarActionPerformed
        BuscarPessoa teladeexclusao = new BuscarPessoa();
        Areadetrabalho.add(teladeexclusao);
        teladeexclusao.setVisible(true);
        teladeexclusao.setSize(826,477);
        teladeexclusao.setLocation(Areadetrabalho.getWidth()/2-teladeexclusao.getWidth()/2,
                Areadetrabalho.getHeight()/2-teladeexclusao.getHeight()/2);
        BasicInternalFrameUI bi = (BasicInternalFrameUI)teladeexclusao.getUI();
        bi.setNorthPane(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_imAlterarActionPerformed

    private void IMCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IMCadastroActionPerformed
        CadastroVisitante teladecadastro = new CadastroVisitante();
        //Areadetrabalho.add(teladecadastro);
        teladecadastro.setVisible(true);
        teladecadastro.setSize(626,361);
        //teladecadastro.setLocation(Areadetrabalho.getWidth()/2-teladecadastro.getWidth()/2, 
          //      Areadetrabalho.getHeight()/2-teladecadastro.getHeight()/2);
        //BasicInternalFrameUI bi =(BasicInternalFrameUI)teladecadastro.getUI();
        //bi.setNorthPane(null);
        teladecadastro.setLocationRelativeTo(null);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_IMCadastroActionPerformed
      
    private void lLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lLoginMouseClicked
        Login login = new Login();
        //Areadetrabalho.add(login);
        login.setVisible(true);
        login.setSize(572, 380);
        login.setLocationRelativeTo(null);
        
        //login.setLocation(Areadetrabalho.getWidth()/2-login.getWidth()/2, 
        // Areadetrabalho.getHeight()/2-login.getHeight()/2);
        //BasicInternalFrameUI bi =(BasicInternalFrameUI)login.getUI();
        //bi.setNorthPane(null);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_lLoginMouseClicked

    private void lAmbienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lAmbienteMouseClicked
        ambientes ambientes = new ambientes();
        Areadetrabalho.add(ambientes);
        ambientes.setVisible(true);
        ambientes.setSize(1400,800);
        ambientes.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ambientes.setLocation(Areadetrabalho.getWidth()/2-ambientes.getWidth()/2, 
        Areadetrabalho.getHeight()/2-ambientes.getHeight()/3);
        ambientes.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi =(BasicInternalFrameUI)ambientes.getUI();
        bi.setNorthPane(null);
        //ambientes.setExtendedState(JFrame.MAXIMIZED_BOTH);
           // TODO add your handling code here:
    }//GEN-LAST:event_lAmbienteMouseClicked

    private void imCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imCadFuncionarioActionPerformed
        CadastroFuncionario cadastrofuncionario = new CadastroFuncionario();
        Areadetrabalho.add(cadastrofuncionario);
        cadastrofuncionario.setVisible(true);
        cadastrofuncionario.setSize(649,404);
        cadastrofuncionario.setLocation(Areadetrabalho.getWidth()/2-cadastrofuncionario.getWidth()/2,
                Areadetrabalho.getHeight()/2-cadastrofuncionario.getHeight()/2);
        BasicInternalFrameUI bi = (BasicInternalFrameUI)cadastrofuncionario.getUI();
        bi.setNorthPane(null);
        
    }//GEN-LAST:event_imCadFuncionarioActionPerformed

    private void MCadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MCadastrarMouseEntered

        // TODO add your handling code here:
    }//GEN-LAST:event_MCadastrarMouseEntered

    private void lEventoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lEventoMouseClicked

       agendasemanal semanal = new agendasemanal();
       semanal.setVisible(true);
       semanal.setSize(780,470);
       semanal.setLocationRelativeTo(null);
    }//GEN-LAST:event_lEventoMouseClicked

    private void imCadastroDeAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imCadastroDeAgendaActionPerformed
        Cadastroagenda cadastroagenda = new Cadastroagenda();
        cadastroagenda.setVisible(true);
        cadastroagenda.setSize(780,470);
        cadastroagenda.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_imCadastroDeAgendaActionPerformed

    private void lLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lLogoMouseClicked
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_lLogoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Areadetrabalho;
    private javax.swing.JMenuItem IMCadastro;
    private javax.swing.JMenu MCadastrar;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem imAlterar;
    private javax.swing.JMenuItem imCadFuncionario;
    private javax.swing.JMenuItem imCadastroDeAgenda;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JLabel lAba;
    private javax.swing.JLabel lAmbiente;
    private javax.swing.JLabel lEvento;
    private javax.swing.JLabel lFundo;
    private javax.swing.JLabel lLogin;
    private javax.swing.JLabel lLogo;
    // End of variables declaration//GEN-END:variables

    void setExtendedState(boolean maximizable) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
